//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSASData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_TransactionMaster
    {
        public string ReferenceId { get; set; }
        public string DocumentId { get; set; }
        public Nullable<System.DateTime> DocumentSubmitDate { get; set; }
        public Nullable<bool> IsHardCopy { get; set; }
        public Nullable<bool> IsSoftCopy { get; set; }
        public string SoftCopyReferencePath { get; set; }
        public Nullable<bool> IsDocumentReturned { get; set; }
        public Nullable<System.DateTime> DocumentReturnDate { get; set; }
        public string DocumentReturnedBy { get; set; }
        public string TransactionCategory { get; set; }
        public string CBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string MBy { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
        public int DocTrnID { get; set; }
    
        public virtual School_DocMaster School_DocMaster { get; set; }
    }
}
