//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSASData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee_ClassWiseDue
    {
        public int RecordId { get; set; }
        public string ClsID { get; set; }
        public string SecID { get; set; }
        public string HeadID { get; set; }
        public Nullable<int> Amount { get; set; }
        public string StructID { get; set; }
        public string InstallID { get; set; }
    }
}
