//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSASData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merit_TransactionMaster
    {
        public string ReferenceId { get; set; }
        public string ParameterId { get; set; }
        public string CBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string MBy { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
        public int MeritID { get; set; }
    
        public virtual School_MeritParameterMaster School_MeritParameterMaster { get; set; }
    }
}
