//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSASData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_RoleMaster
    {
        public string RoleID { get; set; }
        public string RoleName { get; set; }
        public string MenuName { get; set; }
        public Nullable<short> ModuleId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> PrintOrder { get; set; }
        public Nullable<int> CBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<int> MBy { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
    
        public virtual School_AuthModuleMaster School_AuthModuleMaster { get; set; }
    }
}
