//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSASData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_StaffDetailMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff_StaffDetailMaster()
        {
            this.Student_AdmissionMaster = new HashSet<Student_AdmissionMaster>();
        }
    
        public string StaffID { get; set; }
        public string Sex { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public byte[] StaffImg { get; set; }
        public Nullable<System.DateTime> StaffDOB { get; set; }
        public string Cat { get; set; }
        public string Relgn { get; set; }
        public string Mob { get; set; }
        public string Email { get; set; }
        public string Nationality { get; set; }
        public string BldGrp { get; set; }
        public Nullable<int> Age { get; set; }
        public string MStatus { get; set; }
        public string Qualif { get; set; }
        public string AOI { get; set; }
        public Nullable<double> TExp { get; set; }
        public Nullable<double> IExp { get; set; }
        public Nullable<double> OExp { get; set; }
        public Nullable<double> TotExp { get; set; }
        public string StaffCode { get; set; }
        public string Wing { get; set; }
        public string StaffGrp { get; set; }
        public string Dept { get; set; }
        public string Desig { get; set; }
        public Nullable<System.DateTime> StaffDOJ { get; set; }
        public string Bank { get; set; }
        public string StaffType { get; set; }
        public string BankIFSC { get; set; }
        public string BankNo { get; set; }
        public string Pancard { get; set; }
        public string CurrStat { get; set; }
        public Nullable<System.DateTime> StaffDOL { get; set; }
        public string LReason { get; set; }
        public string Convenyce { get; set; }
        public string VehNo { get; set; }
        public string FHName { get; set; }
        public string MotherName { get; set; }
        public string ContactNo { get; set; }
        public string EmergNo { get; set; }
        public string StaffRef1 { get; set; }
        public string Ref1Workin { get; set; }
        public string Ref1IDType { get; set; }
        public string Ref1IDNo { get; set; }
        public string StaffRef2 { get; set; }
        public string Ref2Workin { get; set; }
        public string Ref2IDType { get; set; }
        public string Ref2IDNo { get; set; }
        public string CorrAdd { get; set; }
        public string CorrArea { get; set; }
        public string CorrCity { get; set; }
        public string CorrState { get; set; }
        public string CorrCountry { get; set; }
        public string CorrPinCode { get; set; }
        public string CorrMobile { get; set; }
        public string CorrPhNo1 { get; set; }
        public string CorrPhNo2 { get; set; }
        public string PermAdd { get; set; }
        public string PermArea { get; set; }
        public string PermCity { get; set; }
        public string PermState { get; set; }
        public string PermCountry { get; set; }
        public string PermPinCode { get; set; }
        public string PermMobile { get; set; }
        public string PermPh1 { get; set; }
        public string PermPh2 { get; set; }
        public Nullable<bool> Active { get; set; }
        public string JoinSession { get; set; }
        public Nullable<int> TG { get; set; }
        public Nullable<int> Shft { get; set; }
        public string PunchCode { get; set; }
        public Nullable<bool> SGS { get; set; }
        public Nullable<bool> SGA { get; set; }
        public Nullable<bool> SGM { get; set; }
        public Nullable<int> CBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<int> MBy { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
    
        public virtual School_BloodGroupMaster School_BloodGroupMaster { get; set; }
        public virtual School_CategoryMaster School_CategoryMaster { get; set; }
        public virtual School_DesignationMaster School_DesignationMaster { get; set; }
        public virtual School_NationalityMaster School_NationalityMaster { get; set; }
        public virtual School_QualificationMaster School_QualificationMaster { get; set; }
        public virtual School_ReligonMaster School_ReligonMaster { get; set; }
        public virtual Staff_DeptMaster Staff_DeptMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_AdmissionMaster> Student_AdmissionMaster { get; set; }
    }
}
