//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSASData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_TimeGroupMaster
    {
        public int TGID { get; set; }
        public string TGName { get; set; }
        public Nullable<System.TimeSpan> LateArrivalAllow { get; set; }
        public Nullable<System.TimeSpan> EarlyDepAllow { get; set; }
        public Nullable<System.TimeSpan> EArrivalIgnore { get; set; }
        public Nullable<System.TimeSpan> LateDeptIgnore { get; set; }
        public Nullable<System.TimeSpan> HDLateArrival { get; set; }
        public Nullable<System.TimeSpan> FDLateArrival { get; set; }
        public Nullable<double> OverTimeCalRate { get; set; }
        public Nullable<System.TimeSpan> OverTimeIgnore { get; set; }
        public Nullable<int> LateMonthNo { get; set; }
        public string LateMonthNoResult { get; set; }
        public Nullable<int> EarlyMonthNo { get; set; }
        public string EarllyMonthNoResult { get; set; }
    }
}
