//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iSASData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_RegistrationMaster
    {
        public string Sess { get; set; }
        public string RegClassId { get; set; }
        public string RegID { get; set; }
        public string FormID { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string AdmCategoryId { get; set; }
        public Nullable<int> Amt { get; set; }
        public Nullable<System.DateTime> IntrvwDate { get; set; }
        public string Remark { get; set; }
        public string Student_FirstName { get; set; }
        public string Student_MiddleName { get; set; }
        public string Student_LastName { get; set; }
        public string Student_Gender { get; set; }
        public Nullable<System.DateTime> Student_DOB { get; set; }
        public string Father_FirstName { get; set; }
        public string Father_MiddleName { get; set; }
        public string Father_LastName { get; set; }
        public string Father_MoblieNo { get; set; }
        public string Mother_FirstName { get; set; }
        public string Mother_MiddleName { get; set; }
        public string Mother_LastName { get; set; }
        public string Mother_MobileNo { get; set; }
        public string Student_CorrAdd { get; set; }
        public string Student_CorrArea { get; set; }
        public string Student_CorrCity { get; set; }
        public string Student_CorrState { get; set; }
        public string Student_CorrCountry { get; set; }
        public string Student_CorrMobile { get; set; }
        public string Student_PermAdd { get; set; }
        public string Student_PermArea { get; set; }
        public string Student_PermCity { get; set; }
        public string Student_PermState { get; set; }
        public string Student_PermCountry { get; set; }
        public string Student_PermMobile { get; set; }
        public string RegStatus { get; set; }
        public string CBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string MBy { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
    
        public virtual School_AreaMaster School_AreaMaster { get; set; }
        public virtual School_AreaMaster School_AreaMaster1 { get; set; }
        public virtual School_CityMaster School_CityMaster { get; set; }
        public virtual School_CityMaster School_CityMaster1 { get; set; }
        public virtual School_ClassMaster School_ClassMaster { get; set; }
        public virtual School_CountryMaster School_CountryMaster { get; set; }
        public virtual School_CountryMaster School_CountryMaster1 { get; set; }
        public virtual School_StateMaster School_StateMaster { get; set; }
        public virtual School_StateMaster School_StateMaster1 { get; set; }
    }
}
