//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISas.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_SubjectMaster
    {
        public string SubjectId { get; set; }
        public string SubjectName { get; set; }
        public string SubjectDisplayName { get; set; }
        public Nullable<bool> IsMainSubject { get; set; }
        public Nullable<bool> IsParentSubject { get; set; }
        public Nullable<bool> IsChildSubject { get; set; }
        public Nullable<bool> IsMarkBased { get; set; }
        public Nullable<bool> IsGradeBased { get; set; }
        public Nullable<bool> IsTheorySubject { get; set; }
        public Nullable<bool> ISPracticalSubject { get; set; }
        public Nullable<bool> IsOptionalSubject { get; set; }
        public Nullable<bool> IsCompulsorySubject { get; set; }
        public Nullable<bool> IsAcademicSubject { get; set; }
        public Nullable<bool> IsNonAcademicSubject { get; set; }
        public Nullable<bool> IsCoScholasticSubject { get; set; }
        public string ParentSubjectId { get; set; }
        public string MainSubjectId { get; set; }
        public Nullable<bool> IsWS { get; set; }
        public Nullable<bool> IsCA { get; set; }
        public Nullable<int> PrintOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
