//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISas.Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iSAS_BVSEntities : DbContext
    {
        public iSAS_BVSEntities()
            : base("name=iSAS_BVSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Document_TransactionMaster> Document_TransactionMaster { get; set; }
        public DbSet<Exam_AssessmentMaster> Exam_AssessmentMaster { get; set; }
        public DbSet<Exam_ExamMaster> Exam_ExamMaster { get; set; }
        public DbSet<Exam_GradingMaster> Exam_GradingMaster { get; set; }
        public DbSet<Exam_SubjectMaster> Exam_SubjectMaster { get; set; }
        public DbSet<Fee_StructureMaster> Fee_StructureMaster { get; set; }
        public DbSet<Merit_TransactionMaster> Merit_TransactionMaster { get; set; }
        public DbSet<School_AdmissionCategory> School_AdmissionCategory { get; set; }
        public DbSet<School_AreaMaster> School_AreaMaster { get; set; }
        public DbSet<School_AuthModuleMaster> School_AuthModuleMaster { get; set; }
        public DbSet<School_BloodGroupMaster> School_BloodGroupMaster { get; set; }
        public DbSet<School_CategoryMaster> School_CategoryMaster { get; set; }
        public DbSet<School_CityMaster> School_CityMaster { get; set; }
        public DbSet<School_ClassMaster> School_ClassMaster { get; set; }
        public DbSet<School_ClubMaster> School_ClubMaster { get; set; }
        public DbSet<School_CountryMaster> School_CountryMaster { get; set; }
        public DbSet<School_DesignationMaster> School_DesignationMaster { get; set; }
        public DbSet<School_DocMaster> School_DocMaster { get; set; }
        public DbSet<School_DocumentMaster> School_DocumentMaster { get; set; }
        public DbSet<School_HouseMaster> School_HouseMaster { get; set; }
        public DbSet<School_MeritParameterMaster> School_MeritParameterMaster { get; set; }
        public DbSet<School_MinorityCategoryMaster> School_MinorityCategoryMaster { get; set; }
        public DbSet<School_NationalityMaster> School_NationalityMaster { get; set; }
        public DbSet<School_ProfessionMaster> School_ProfessionMaster { get; set; }
        public DbSet<School_QualificationMaster> School_QualificationMaster { get; set; }
        public DbSet<School_ReligonMaster> School_ReligonMaster { get; set; }
        public DbSet<School_RoleMaster> School_RoleMaster { get; set; }
        public DbSet<School_SectionMaster> School_SectionMaster { get; set; }
        public DbSet<School_SessionMaster> School_SessionMaster { get; set; }
        public DbSet<School_StateMaster> School_StateMaster { get; set; }
        public DbSet<School_UserRoleMaster> School_UserRoleMaster { get; set; }
        public DbSet<School_UsersInfo> School_UsersInfo { get; set; }
        public DbSet<School_WingMaster> School_WingMaster { get; set; }
        public DbSet<Staff_DeptMaster> Staff_DeptMaster { get; set; }
        public DbSet<Staff_ShiftMaster> Staff_ShiftMaster { get; set; }
        public DbSet<Staff_StaffDetailMaster> Staff_StaffDetailMaster { get; set; }
        public DbSet<Staff_TimeGroupMaster> Staff_TimeGroupMaster { get; set; }
        public DbSet<Student_AdmissionMaster> Student_AdmissionMaster { get; set; }
        public DbSet<Student_RegistrationMaster> Student_RegistrationMaster { get; set; }
        public DbSet<Transport_PickedUpBy> Transport_PickedUpBy { get; set; }
        public DbSet<Transport_RouteMaster> Transport_RouteMaster { get; set; }
        public DbSet<Transport_StopMaster> Transport_StopMaster { get; set; }
        public DbSet<Transport_TransportMode> Transport_TransportMode { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<Fee_ClassWiseDue> Fee_ClassWiseDue { get; set; }
        public DbSet<Outbox> Outboxes { get; set; }
        public DbSet<Sent> Sents { get; set; }
        public DbSet<SMS_GroupMaster> SMS_GroupMaster { get; set; }
        public DbSet<Strength> Strengths { get; set; }
    }
}
