//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISas.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outbox
    {
        public string MobileNo { get; set; }
        public string SMSText { get; set; }
        public string ReciverName { get; set; }
        public string RecordSendBy { get; set; }
        public System.DateTime RecordSendDate { get; set; }
        public System.DateTime SendDate { get; set; }
    }
}
