//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISas.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_AdmissionCategory
    {
        public string AdmCategoryId { get; set; }
        public string AdmCategoryName { get; set; }
        public Nullable<bool> Default { get; set; }
        public Nullable<byte> PrintOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string MBy { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
    }
}
