//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISas.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_MeritParameterMaster
    {
        public School_MeritParameterMaster()
        {
            this.Merit_TransactionMaster = new HashSet<Merit_TransactionMaster>();
        }
    
        public string ParameterId { get; set; }
        public string ParameterName { get; set; }
        public Nullable<int> ParameterPointValue { get; set; }
        public string ParameterCategory { get; set; }
        public Nullable<bool> ParameterForStudent { get; set; }
        public Nullable<bool> ParameterStaff { get; set; }
        public Nullable<byte> PrintOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string MBy { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
    
        public virtual ICollection<Merit_TransactionMaster> Merit_TransactionMaster { get; set; }
    }
}
