//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISas.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_AuthModuleMaster
    {
        public School_AuthModuleMaster()
        {
            this.School_RoleMaster = new HashSet<School_RoleMaster>();
        }
    
        public short ID { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> Order { get; set; }
        public byte[] FolderImage { get; set; }
    
        public virtual ICollection<School_RoleMaster> School_RoleMaster { get; set; }
    }
}
