//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISas.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_ClassMaster
    {
        public School_ClassMaster()
        {
            this.School_ClassMaster1 = new HashSet<School_ClassMaster>();
            this.Student_AdmissionMaster = new HashSet<Student_AdmissionMaster>();
            this.Student_AdmissionMaster1 = new HashSet<Student_AdmissionMaster>();
            this.Student_RegistrationMaster = new HashSet<Student_RegistrationMaster>();
        }
    
        public string ClassID { get; set; }
        public string ClassName { get; set; }
        public string WingID { get; set; }
        public Nullable<int> RealClass { get; set; }
        public string PromotedClass { get; set; }
        public Nullable<byte> PrintOrder { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsAlumniClass { get; set; }
        public Nullable<int> CBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<int> MBy { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
    
        public virtual ICollection<School_ClassMaster> School_ClassMaster1 { get; set; }
        public virtual School_ClassMaster School_ClassMaster2 { get; set; }
        public virtual School_WingMaster School_WingMaster { get; set; }
        public virtual ICollection<Student_AdmissionMaster> Student_AdmissionMaster { get; set; }
        public virtual ICollection<Student_AdmissionMaster> Student_AdmissionMaster1 { get; set; }
        public virtual ICollection<Student_RegistrationMaster> Student_RegistrationMaster { get; set; }
    }
}
