//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISas.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class School_DocMaster
    {
        public School_DocMaster()
        {
            this.Document_TransactionMaster = new HashSet<Document_TransactionMaster>();
        }
    
        public string DocumentId { get; set; }
        public string DocumentName { get; set; }
        public Nullable<bool> IsDocumentForStaff { get; set; }
        public Nullable<bool> IsDocumentForStudent { get; set; }
        public Nullable<bool> IsDocumentMandatory { get; set; }
        public Nullable<bool> IsDocumentHardCopy { get; set; }
        public Nullable<bool> IsDocumentSoftCopy { get; set; }
        public Nullable<bool> IsOriginalRequired { get; set; }
        public Nullable<bool> IsReturnable { get; set; }
        public Nullable<byte> PrintOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public string MBy { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
    
        public virtual ICollection<Document_TransactionMaster> Document_TransactionMaster { get; set; }
    }
}
