//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISas.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sent
    {
        public Nullable<long> smsid { get; set; }
        public string MobileNo { get; set; }
        public string SMSText { get; set; }
        public string ReciverName { get; set; }
        public string SendBy { get; set; }
        public Nullable<System.DateTime> SendDateTime { get; set; }
        public Nullable<System.DateTime> ActualSendDat { get; set; }
        public string ActualSendBy { get; set; }
    }
}
