//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISas.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_ShiftMaster
    {
        public int SID { get; set; }
        public string ShiftName { get; set; }
        public string NightShift { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public Nullable<System.TimeSpan> WorkingHrs { get; set; }
        public Nullable<System.TimeSpan> HDStart { get; set; }
        public Nullable<System.TimeSpan> HDEnd { get; set; }
        public Nullable<System.TimeSpan> HDHrs { get; set; }
        public Nullable<System.TimeSpan> RestIn { get; set; }
        public Nullable<System.TimeSpan> RestOut { get; set; }
        public Nullable<System.TimeSpan> RestHrs { get; set; }
        public Nullable<System.TimeSpan> AbsentWorkingHrsLess { get; set; }
        public Nullable<System.TimeSpan> HDWorkingHrsLess { get; set; }
        public Nullable<System.TimeSpan> OTAllowed { get; set; }
        public string C1stWO { get; set; }
        public string C2ndWO { get; set; }
        public Nullable<bool> C1Sat { get; set; }
        public Nullable<bool> C2Sat { get; set; }
        public Nullable<bool> C3Sat { get; set; }
        public Nullable<bool> C4Sat { get; set; }
        public Nullable<bool> C5Sat { get; set; }
        public Nullable<bool> C1SatHD { get; set; }
        public Nullable<bool> C2SatHD { get; set; }
        public Nullable<bool> C3SatHD { get; set; }
        public Nullable<bool> C4SatHD { get; set; }
        public Nullable<bool> C5SatHD { get; set; }
        public string LastWorkingDay { get; set; }
        public Nullable<int> CBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<int> MBy { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
    }
}
