//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISas.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_AdmissionMaster
    {
        public string Stud_Wing { get; set; }
        public string Stud_RegNo { get; set; }
        public string Stud_AdmNo { get; set; }
        public string Stud_UID { get; set; }
        public Nullable<System.DateTime> Stud_DOA { get; set; }
        public Nullable<bool> Stud_Staffward { get; set; }
        public string Stud_StaffwardID { get; set; }
        public Nullable<bool> NewAdm { get; set; }
        public Nullable<bool> OldAdm { get; set; }
        public string Stud_Gender { get; set; }
        public string Stud_Parents { get; set; }
        public Nullable<System.DateTime> Stud_DOB { get; set; }
        public string Stud_BirthPlace { get; set; }
        public string Stud_FirstName { get; set; }
        public string Stud_MiddleName { get; set; }
        public string Stud_LastName { get; set; }
        public string Stud_Class { get; set; }
        public string Stud_Section { get; set; }
        public Nullable<int> Stud_ClassRollNo { get; set; }
        public string Stud_RollNo { get; set; }
        public string Stud_BldGrp { get; set; }
        public string Stud_House { get; set; }
        public Nullable<int> Stud_Club { get; set; }
        public string Stud_Category { get; set; }
        public string Stud_Religion { get; set; }
        public string Stud_MCategory { get; set; }
        public string Stud_Nationality { get; set; }
        public string Stud_Aadhar { get; set; }
        public string Stud_Height { get; set; }
        public string Stud_Weight { get; set; }
        public Nullable<int> Stud_Age { get; set; }
        public string AdmClass { get; set; }
        public string Stud_Emailadd { get; set; }
        public string Stud_LastSchool { get; set; }
        public string Stud_LastBoard { get; set; }
        public string Stud_LastBoardLocation { get; set; }
        public string Stud_LastBoardNo { get; set; }
        public string Stud_LastClass { get; set; }
        public Nullable<int> Stud_Noofyearattend { get; set; }
        public string Stud_LastPer { get; set; }
        public string Stud_LastAchievement { get; set; }
        public string Stud_MProblem { get; set; }
        public string Stud_MDoctor { get; set; }
        public string Stud_MAllergyMedicine { get; set; }
        public string Stud_MClinicAdd { get; set; }
        public string Stud_BS1Name { get; set; }
        public Nullable<short> Stud_BS1Age { get; set; }
        public string Stud_BS1Gender { get; set; }
        public string Stud_BS1Class { get; set; }
        public string Stud_BS1Institute { get; set; }
        public string Stud_BS2Name { get; set; }
        public Nullable<short> Stud_BS2Age { get; set; }
        public string Stud_BS2Gender { get; set; }
        public string Stud_BS2Class { get; set; }
        public string Stud_BS2Institute { get; set; }
        public string Stud_BS3Name { get; set; }
        public Nullable<short> Stud_BS3Age { get; set; }
        public string Stud_BS3Gender { get; set; }
        public string Stud_BS3Class { get; set; }
        public string Stud_BS3Institute { get; set; }
        public Nullable<bool> sibling { get; set; }
        public string Stud_SiblingUID { get; set; }
        public byte[] Stud_Image { get; set; }
        public string Stud_Activity { get; set; }
        public string Father_FirstName { get; set; }
        public string Father_MiddleName { get; set; }
        public string Father_LastName { get; set; }
        public string Father_Qualif { get; set; }
        public string Father_Prof { get; set; }
        public string Father_Desg { get; set; }
        public string Father_MoblieNo { get; set; }
        public string Father_Aadhar { get; set; }
        public Nullable<int> Father_AnnualIncome { get; set; }
        public Nullable<short> Father_Age { get; set; }
        public string Father_Email { get; set; }
        public Nullable<bool> Father_Alumni { get; set; }
        public string Father_AlumniYear { get; set; }
        public string Father_OffAdd { get; set; }
        public string Father_Area { get; set; }
        public string Father_City { get; set; }
        public string Father_State { get; set; }
        public string Father_Country { get; set; }
        public string Father_PinCode { get; set; }
        public string Father_OffNo { get; set; }
        public string Father_FaxNo { get; set; }
        public byte[] Father_Image { get; set; }
        public string Mother_FirstName { get; set; }
        public string Mother_MiddleName { get; set; }
        public string Mother_LastName { get; set; }
        public string Mother_Qualif { get; set; }
        public string Mother_Prpf { get; set; }
        public string Mother_Desg { get; set; }
        public string Mother_MobileNo { get; set; }
        public string Mother_Aadhar { get; set; }
        public Nullable<int> Mother_AnnualIncome { get; set; }
        public Nullable<int> Mother_Age { get; set; }
        public string Mother_Email { get; set; }
        public Nullable<bool> Mother_Alumni { get; set; }
        public string Mother_AlumniYear { get; set; }
        public string Mother_OffAdd { get; set; }
        public string Mother_Area { get; set; }
        public string Mother_City { get; set; }
        public string Mother_State { get; set; }
        public string Mother_Country { get; set; }
        public string Mother_Pincode { get; set; }
        public string Mother_OffNo { get; set; }
        public string Mother_FaxNo { get; set; }
        public byte[] Mother_Image { get; set; }
        public string Gardian_FirstName { get; set; }
        public string Gardian_MiddleName { get; set; }
        public string Gardian_LastName { get; set; }
        public string Gardian_Qualif { get; set; }
        public string Gardian_Prof { get; set; }
        public string Gardian_Desg { get; set; }
        public string Gardian_MobileNo { get; set; }
        public string Gardian_Aadhar { get; set; }
        public Nullable<int> Gardian_AnnualIncome { get; set; }
        public Nullable<short> Gardian_Age { get; set; }
        public string Gardian_Email { get; set; }
        public Nullable<bool> Gardian_Alumni { get; set; }
        public string Gardian_AlumniYear { get; set; }
        public string Gardian_Relation { get; set; }
        public string Gardian_OffAdd { get; set; }
        public string Gardian_Area { get; set; }
        public string Gardian_City { get; set; }
        public string Gardian_State { get; set; }
        public string Gardian_PinCode { get; set; }
        public string Gardian_Country { get; set; }
        public string Gardian_OffNo { get; set; }
        public string Gardian_FaxNo { get; set; }
        public byte[] Gardian_image { get; set; }
        public string Stud_CorrAdd { get; set; }
        public string Stud_CorrArea { get; set; }
        public string Stud_CorrCity { get; set; }
        public string Stud_CorrState { get; set; }
        public string Stud_CorrCountry { get; set; }
        public string Stud_CorrPinCode { get; set; }
        public string Stud_CorrMobile { get; set; }
        public string Stud_CorrPhNo1 { get; set; }
        public string Stud_CorrPhNo2 { get; set; }
        public string Stud_PermAdd { get; set; }
        public string Stud_PermArea { get; set; }
        public string Stud_PermCity { get; set; }
        public string Stud_PermState { get; set; }
        public string Stud_PermCountry { get; set; }
        public string Stud_PermPinCode { get; set; }
        public string Stud_PermMobile { get; set; }
        public string Stud_PermPh1 { get; set; }
        public string Stud_PermPh2 { get; set; }
        public Nullable<System.DateTime> Father_birthday { get; set; }
        public Nullable<System.DateTime> Mother_birthday { get; set; }
        public Nullable<System.DateTime> Fat_MotAnniver { get; set; }
        public string Father_Hobby { get; set; }
        public string Mother_Hobby { get; set; }
        public string Stud_ChildSuspended { get; set; }
        public string Stud_Support { get; set; }
        public string Stud_Ref { get; set; }
        public string Stud_IdentMark { get; set; }
        public string Stud_ReasonJoin { get; set; }
        public Nullable<bool> Stud_HostelReq { get; set; }
        public Nullable<bool> Stud_TransReq { get; set; }
        public string Stud_InternetReq { get; set; }
        public string Stud_Convence { get; set; }
        public string Stud_Suggestion { get; set; }
        public string Stud_LocalRefName1 { get; set; }
        public string Stud_LocalRefName2 { get; set; }
        public string Stud_LocalRef1Add { get; set; }
        public string Stud_LocalRef2Add { get; set; }
        public string Stud_LocalRef1Relation { get; set; }
        public string Stud_LocalRef2Relation { get; set; }
        public string Stud_LocalRef1Contact { get; set; }
        public string Stud_LocalRef2Contact { get; set; }
        public string Remark { get; set; }
        public string Stud_OldTcNo { get; set; }
        public string Stud_OldReasonToLeave { get; set; }
        public string Stud_LastSchoolAdd { get; set; }
        public string Stud_UniversityNo { get; set; }
        public string Stud_FeeStruct { get; set; }
        public Nullable<decimal> Stud_RefundAmt { get; set; }
        public string Stud_TotalFamilyMem { get; set; }
        public Nullable<decimal> Stud_FamilyIncome { get; set; }
        public Nullable<bool> SameAddress { get; set; }
        public Nullable<bool> NSO { get; set; }
        public Nullable<bool> TC { get; set; }
        public Nullable<bool> Suspend { get; set; }
        public Nullable<short> Session { get; set; }
        public string AdmSession { get; set; }
        public Nullable<bool> Doc1 { get; set; }
        public Nullable<bool> Doc2 { get; set; }
        public Nullable<bool> Doc3 { get; set; }
        public Nullable<bool> Doc4 { get; set; }
        public Nullable<bool> Doc5 { get; set; }
        public Nullable<bool> Doc6 { get; set; }
        public Nullable<bool> Doc7 { get; set; }
        public Nullable<bool> Doc8 { get; set; }
        public Nullable<bool> Doc9 { get; set; }
        public Nullable<bool> Doc10 { get; set; }
        public Nullable<int> PRouteId { get; set; }
        public Nullable<int> PStopId { get; set; }
        public string Facility { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<int> DRouteId { get; set; }
        public Nullable<int> DStopId { get; set; }
        public Nullable<int> ModeofTransport { get; set; }
        public Nullable<int> PickedupBy { get; set; }
        public Nullable<bool> AvailSMS { get; set; }
        public Nullable<bool> SMSF { get; set; }
        public Nullable<bool> SMSM { get; set; }
        public Nullable<bool> SMSG { get; set; }
        public Nullable<bool> SMSO { get; set; }
        public Nullable<bool> AvailSnacks { get; set; }
        public Nullable<bool> Doctoroncall { get; set; }
        public string SMSNo { get; set; }
        public Nullable<int> CBy { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<int> MBy { get; set; }
        public Nullable<System.DateTime> MDate { get; set; }
    
        public virtual Fee_StructureMaster Fee_StructureMaster { get; set; }
        public virtual School_AreaMaster School_AreaMaster { get; set; }
        public virtual School_AreaMaster School_AreaMaster1 { get; set; }
        public virtual School_AreaMaster School_AreaMaster2 { get; set; }
        public virtual School_AreaMaster School_AreaMaster3 { get; set; }
        public virtual School_AreaMaster School_AreaMaster4 { get; set; }
        public virtual School_BloodGroupMaster School_BloodGroupMaster { get; set; }
        public virtual School_CategoryMaster School_CategoryMaster { get; set; }
        public virtual School_CityMaster School_CityMaster { get; set; }
        public virtual School_CityMaster School_CityMaster1 { get; set; }
        public virtual School_CityMaster School_CityMaster2 { get; set; }
        public virtual School_CityMaster School_CityMaster3 { get; set; }
        public virtual School_CityMaster School_CityMaster4 { get; set; }
        public virtual School_ClassMaster School_ClassMaster { get; set; }
        public virtual School_ClassMaster School_ClassMaster1 { get; set; }
        public virtual School_ClubMaster School_ClubMaster { get; set; }
        public virtual School_CountryMaster School_CountryMaster { get; set; }
        public virtual School_CountryMaster School_CountryMaster1 { get; set; }
        public virtual School_CountryMaster School_CountryMaster2 { get; set; }
        public virtual School_CountryMaster School_CountryMaster3 { get; set; }
        public virtual School_CountryMaster School_CountryMaster4 { get; set; }
        public virtual School_HouseMaster School_HouseMaster { get; set; }
        public virtual School_MinorityCategoryMaster School_MinorityCategoryMaster { get; set; }
        public virtual School_NationalityMaster School_NationalityMaster { get; set; }
        public virtual School_ProfessionMaster School_ProfessionMaster { get; set; }
        public virtual School_ProfessionMaster School_ProfessionMaster1 { get; set; }
        public virtual School_ProfessionMaster School_ProfessionMaster2 { get; set; }
        public virtual School_QualificationMaster School_QualificationMaster { get; set; }
        public virtual School_QualificationMaster School_QualificationMaster1 { get; set; }
        public virtual School_QualificationMaster School_QualificationMaster2 { get; set; }
        public virtual School_ReligonMaster School_ReligonMaster { get; set; }
        public virtual School_SectionMaster School_SectionMaster { get; set; }
        public virtual School_SessionMaster School_SessionMaster { get; set; }
        public virtual School_StateMaster School_StateMaster { get; set; }
        public virtual School_StateMaster School_StateMaster1 { get; set; }
        public virtual School_StateMaster School_StateMaster2 { get; set; }
        public virtual School_StateMaster School_StateMaster3 { get; set; }
        public virtual School_StateMaster School_StateMaster4 { get; set; }
        public virtual School_WingMaster School_WingMaster { get; set; }
        public virtual Staff_StaffDetailMaster Staff_StaffDetailMaster { get; set; }
        public virtual Transport_RouteMaster Transport_RouteMaster { get; set; }
        public virtual Transport_StopMaster Transport_StopMaster { get; set; }
        public virtual Transport_TransportMode Transport_TransportMode { get; set; }
        public virtual Transport_PickedUpBy Transport_PickedUpBy { get; set; }
        public virtual Transport_RouteMaster Transport_RouteMaster1 { get; set; }
        public virtual Transport_StopMaster Transport_StopMaster1 { get; set; }
    }
}
